[project]
name = "aspect-rules-py"
version = "0.0.0"
description = "aspect_rules_py example"
requires-python = ">=3.13"

classifiers = [
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.13",
]

dependencies = [
  "absl-py",
]
